[2024-04-10 09:51:48,468] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:51:48] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:51:48,470] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:51:48] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:51:48,471] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:51:48] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:51:48,472] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:51:48] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:51:48,512] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:51:48] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:52:17,631] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:52:17] "GET /pendencias?nome=Teste HTTP/1.1" 200 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:52:34,393] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:52:34] "DELETE /pendencia?nome=Vazamento%20de%20agua%20do%20equipamento%202 HTTP/1.1" 200 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:52:57,108] WARNING del_produto() L138  Erro ao deletar pendenica #'Vazamento de oleo do equipamento 1', pendencia n√£o encontrado na base :/ - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/app.py L138 
[2024-04-10 09:52:57,109] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:52:57] "[33mDELETE /pendencia?nome=Vazamento%20de%20oleo%20do%20equipamento%201 HTTP/1.1[0m" 404 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:53:10,092] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:53:10] "DELETE /pendencia?nome=Vazamento%20de%20√≥leo%20do%20equipamento%201 HTTP/1.1" 200 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:53:21,489] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:53:21] "POST /pendencia HTTP/1.1" 200 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:53:31,730] WARNING add_pendencia() L57   Erro ao adicionar produto 'Vazamento de √≥leo do equipamento 2', Pendencia de mesmo nome j√° salvo na base :/ - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/app.py L57  
[2024-04-10 09:53:31,730] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 09:53:31] "[31m[1mPOST /pendencia HTTP/1.1[0m" 409 - - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 09:54:14,822] INFO _log() L96    * Detected change in '/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/model/pendencia.py', reloading - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/env/lib/python3.12/site-packages/werkzeug/_internal.py L96  
